### PR TITLE
Page and static prefix support proposal for koenbok/Cactus#177

### PR DESCRIPTION
**Pull request by kartoch**
- Add a 'page-prefix' and 'static-prefix' for configuration
- Manager prefixes in site._get_url_for_static() and site._get_url_for_page()

### CODE REVIEW

**Comment by krallin** [comment]
A few notes (sorry, I have a lot on the side, so not able to be as reactive as I wish to be):

+ This might break for external URLs (which are returned absolute and would still get the prefix).
+ There's a bit of duplicate logic here, would it make sense to move it to `_get_url`? This would also let you solve the problem of external URLs more easily.
+ Can we get some tests added? Both in cases where `page-prefix` and `static-prefix` are set? 
+ We might also want some docs. Historically we've been bad at this, but no one will find this feature unless it's at least somewhere in the README.
+ Can you briefly explain the use case for this? Not that I don't believe it's useful, but I just want to make sure there aren't other changes we should be making.

Thanks!

**Comment by kartoch** [comment]
> Can you briefly explain the use case for this? Not that I don't believe it's useful, but I just want to make sure there aren't other changes we should be making.

I want to drop my files in http://www.mysite.com/subdir/

There is still a problem: sitemap is generated based on `site-url`, but only uses the main domain name and does not include the prefix.

> This might break for external URLs (which are returned absolute and would still get the prefix).

Ya, that a problem. One (weak) solution is to use normal URL instead of static and url tags.

> There's a bit of duplicate logic here, would it make sense to move it to _get_url? This would also let you solve the problem of external URLs more easily.
> Can we get some tests added? Both in cases where page-prefix and static-prefix are set?
> We might also want some docs. Historically we've been bad at this, but no one will find this feature unless it's at least somewhere in the README.

The final submission will be factorized / optimized, I'm just want feedbacks first to see if mu proposal is interesting and correct.

**Comment by kartoch** [comment]
Tests are working, your turn.

**Comment by kartoch** [comment]
@afrigeri the '/static' pattern is used as-is in the Cactus source, see https://github.com/koenbok/Cactus/commit/c759eee87a24fb337f15df027ab5e979d0453d66#L28 . My proposal is just to add a prefix to it, hence having something like '/my-prefix/static'.

**Comment by geomblog** [comment]
I opened a separate issue, but maybe it's better as a comment here. I used this patch because I had the same use-case. And it works fine. However, I can't do testing any more, because the files in .build all have the site-path encoded in whereas for local testing '/static/...' urls suffice. It's almost as if one needs a 'deploy' option like with S3, but for this purpose. Or have a way to only do the rewrite for the final build instead of testing?

**Comment by kartoch** [comment]
largely outdated

**Pull request closed without merging**
